### ISSUE TITLE
Can't link hard-float modules with soft-float modules

### ISSUE THREAD

**Issue by zhanghongce** [heshamelmatary/seL4-riscv-mk#3]
Not sure if I'm using an inappropriate toolchain or not. This is the error I got when building for Spike according to the instructions here: http://heshamelmatary.blogspot.co.uk/2015/07/howto-build-and-run-sel4-on-risc-v.html

 [CC] src/mapping.o
 [CC] src/ut_manager/bitfield.o
 [CC] src/ut_manager/ut_allocator.o
 [CC] src/ut_manager/ut.o
 [CC] src/sys/debug.o
 [CC] src/sys/panic.o
 [LINK] sos.elf
/home/hongce/rocket/rocket-chip/riscv/lib/gcc/riscv32-unknown-elf/6.1.0/../../../../riscv32-unknown-elf/bin/ld: archive.o: can't link hard-float modules with soft-float modules

I'm using the riscv toolchain provided in the Rocket Chip repo. The toolchain was built with the build-rv32ima.sh script. 

riscv32-unknown-elf-gcc version: 6.1.0

**Comment by heshamelmatary** [comment]
You need to build the RISC-V toolchain with soft-float. Please have a look at a similar issue [here](https://github.com/heshamelmatary/sel4riscv-manifest/issues/1)

**Comment by zhanghongce** [comment]
Thank you! It seems that I'm not using the correct toolchain. I switch to the one mentioned here: https://github.com/dornerworks/seL4-riscv-mk/tree/july_2015_riscv_rocket, and it works. Thanks!

**Comment by heshamelmatary** [comment]
Glad to know it works. I'm closing this issue. 

Please be aware that this is an outdated repo (it's no longer being maintained since 2015). If you are after a newer version, have a look at the blog post updates [here](http://heshamelmatary.blogspot.com.au/).
