### ISSUE TITLE
Can not compile sel4-riscv64

### ISSUE THREAD

**Issue by Ddnirvana** [heshamelmatary/seL4-riscv-mk#4]
Hi @heshamelmatary Hesham,
I am interested to run seL4 on RISCV, and I am very very happy to find that you have done much work to port seL4 to RISCV.

I found you published a "RISC-V unofficial release" on your blog(http://heshamelmatary.blogspot.com.au/2017/06/sel4testrisc-v-unofficial-release-priv.html). 

And I tried to download the ported seL4 from your repo and directly compiled it, however, I failed :(.

Here is the process I have tried:
<pre>
# git clone https://github.com/heshamelmatary/seL4.git -b  
# cd seL4
# git checkout RISCVUnofficialRelease-24062017
# make ARCH=riscv PLAT=spike
</pre>

and then I got the following error messages:

<pre>
[MKDIR] arch/object
 [PBF_GEN] arch/object/structures.pbf
In file included from ./include/arch/riscv/arch/object/structures.bf:13:0:
./include/config.h:17:22: fatal error: autoconf.h: No such file or directory
 #include <autoconf.h>
                      ^
compilation terminated.
make: *** [arch/object/structures.pbf] Error 1
</pre>

And the I checked the configs
<pre>
# ls configs
  am335x  apq8064  exynos4  exynos5  hikey  imx31  imx6  imx7  omap3  pc99  tk1  zynq7000
</pre>

It seems there is no config for spike platform.....

I am not sure I have done correctly... I just want to compile the sel4 kernel...
How can I fix this problem? 

Any advice is welcomed! Thanks a lot!

**Comment by heshamelmatary** [comment]
Hi @Ddnirvana 

There are 2 issues:
1- The kernel is not supposed to be built alone, rather it should be part of a project. Please see the seL4 Getting Started guide here [1].
2- As mentioned in the README, this repo is outdated, you can follow my recent blog posts to get recent versions of sel4test project for example (and how to build/run them).

[1] https://wiki.sel4.systems/Getting%20started
[2] http://heshamelmatary.blogspot.com/
